/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: abdullahyeahyea (https://sketchfab.com/abdullahyeahyea)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cazal-sunglasses-3ead5878ad3140d2a5f17ba2c56901b2
Title: Cazal Sunglasses
*/

import { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

const CazalSunglasses = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/cazal_sunglasses.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <group scale={0.0025} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 46.499, -47.83]}
            rotation={[-1.413, 0, 0]}
            scale={[7.114, 2.838, 7.114]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial.geometry}
              material={materials.BODY}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_1.geometry}
              material={materials.GLASS}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_2.geometry}
              material={materials.FRAME}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_3.geometry}
              material={materials.FRAME_0}
            />
          </group>
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("/cazal_sunglasses.glb");

export default CazalSunglasses;
