/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: assetfactory (https://sketchfab.com/assetfactory)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dark-sunglasses-69d530f7e6bd45b9b3d9f16dae627348
Title: Dark sunglasses
*/

import { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

const DarkSunglasses = forwardRef((props, ref ) => {
    const { nodes, materials } = useGLTF("/dark_sunglasses.glb");
    return (
        <group ref={ref} {...props} dispose={null}>
            <group position={[0, -0.17, 0]} scale={0.01}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube010_BlackPlastic_0.geometry}
                    material={materials.BlackPlastic}
                    position={[0, 18.926, 12.893]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={16.831}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane_BlackGlass_0.geometry}
                    material={materials.BlackGlass}
                    position={[33.463, 18.628, 12.893]}
                    scale={[25.868, 16.113, 15.015]}
                />
            </group>
        </group>
    );
});

useGLTF.preload("/dark_sunglasses.glb");

export default DarkSunglasses;
