/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Lamis (https://sketchfab.com/LamiM)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/glasses-0a51db978635499cbce9cc57c434ffdf
Title: Glasses
*/

import { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

const YellowSunglasses = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/yellow_glasses.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <group scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Glasses__0.geometry}
          material={materials.Glasses}
          position={[0, -184.724, 1.159]}
          rotation={[-0.084, 0, 0]}
          >
          <meshStandardMaterial {...materials.Glasses} depthTest depthWrite />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.L_Temple_Glasses__0.geometry}
          material={materials.Glasses}
          position={[0, 0.002, -0.003]}
          rotation={[0.002, 0, 0]}
          >
          <meshStandardMaterial {...materials.Glasses} transparent={false} depthTest depthWrite />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.R_Temple_Glasses__0.geometry}
          material={materials.Glasses}
          position={[0, 0.002, -0.003]}
          rotation={[0.002, 0, 0]}
          >
          <meshStandardMaterial {...materials.Glasses} transparent={false} depthTest depthWrite />
        </mesh>
      </group>
    </group>
  );
});

useGLTF.preload("/yellow_glasses.glb");

export default YellowSunglasses;
